### ISSUE TITLE
grpcio wheel does not build with Ubuntu 25.04

### ISSUE THREAD

**Issue by rhdunn** [NVIDIA/NeMo#13625]
**Describe the bug**

When trying to install nemo on Ubuntu 25.04 the installation fails while building the grpcio wheel with the error:

```
Collecting grpcio==1.41.0 (from tritonclient[all]->nvidia-pytriton->nemo-toolkit==2.3.0)
...
Building wheels for collected packages: nemo-toolkit, grpcio, pyzmq
  Building editable for nemo-toolkit (pyproject.toml): started
  Building editable for nemo-toolkit (pyproject.toml): finished with status 'done'
  Created wheel for nemo-toolkit: filename=nemo_toolkit-2.3.0-0.editable-py3-none-any.whl size=24517 sha256=3f7fa1cfe25a951251f6f3e6d7317782030afe96c6540a5b7d65e2fc48e5c09f
  Stored in directory: /tmp/pip-ephem-wheel-cache-x2tbdea9/wheels/1d/d4/6f/5db7fbce7e936e3338a23142056af3c78e771997485fb190e9
  Building wheel for grpcio (pyproject.toml): started
  Building wheel for grpcio (pyproject.toml): still running...
  Building wheel for grpcio (pyproject.toml): still running...
  Building wheel for grpcio (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for grpcio (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [3827 lines of output]
...
g++ -std=c++11 -std=c++11 -fPIC -DZMQ_HAVE_CURVE=1 -DZMQ_USE_TWEETNACL=1 -DZMQ_USE_EPOLL=1 -DZMQ_IOTHREADS_USE_EPOLL=1 -DZMQ_POLL_BASED_ON_POLL=1 -Ibundled/zeromq/include -Ibundled -I.../nemo/.venv/include -I/usr/local/include/python3.12 -c bundled/zeromq/src/curve_client.cpp -o build/temp.linux-x86_64-cpython-312/bundled/zeromq/src/curve_client.o
      In file included from /usr/include/c++/14/ext/alloc_traits.h:34,
                       from /usr/include/c++/14/bits/stl_tree.h:67,
                       from /usr/include/c++/14/map:62,
                       from bundled/zeromq/src/metadata.hpp:33,
                       from bundled/zeromq/src/msg.hpp:40,
                       from bundled/zeromq/src/curve_client.cpp:35:
      /usr/include/c++/14/bits/alloc_traits.h: In instantiation of ‘struct std::__allocator_traits_base::__rebind<zmq::secure_allocator_t<unsigned char>, unsigned char, void>’:
      /usr/include/c++/14/bits/alloc_traits.h:133:11:   required by substitution of ‘template<class _Alloc, class _Up> using std::__alloc_rebind = typename std::__allocator_traits_base::__rebind<_Alloc, _Up>::type [with _Alloc = zmq::secure_allocator_t<unsigned char>; _Up = unsigned char]’
        133 |     using __alloc_rebind
            |           ^~~~~~~~~~~~~~
      /usr/include/c++/14/bits/alloc_traits.h:267:8:   required by substitution of ‘template<class _Alloc> template<class _Tp> using std::allocator_traits< <template-parameter-1-1> >::rebind_alloc = std::__alloc_rebind<_Alloc, _Tp> [with _Tp = unsigned char; _Alloc = zmq::secure_allocator_t<unsigned char>]’
        267 |         using rebind_alloc = __alloc_rebind<_Alloc, _Tp>;
            |               ^~~~~~~~~~~~
      /usr/include/c++/14/ext/alloc_traits.h:126:65:   required from ‘struct __gnu_cxx::__alloc_traits<zmq::secure_allocator_t<unsigned char>, unsigned char>::rebind<unsigned char>’
        126 |       { typedef typename _Base_type::template rebind_alloc<_Tp> other; };
            |                                                                 ^~~~~
      /usr/include/c++/14/bits/stl_vector.h:87:21:   required from ‘struct std::_Vector_base<unsigned char, zmq::secure_allocator_t<unsigned char> >’
         87 |         rebind<_Tp>::other _Tp_alloc_type;
            |                            ^~~~~~~~~~~~~~
      /usr/include/c++/14/bits/stl_vector.h:428:11:   required from ‘class std::vector<unsigned char, zmq::secure_allocator_t<unsigned char> >’
        428 |     class vector : protected _Vector_base<_Tp, _Alloc>
            |           ^~~~~~
      bundled/zeromq/src/curve_client_tools.hpp:64:76:   required from here
         64 |         std::vector<uint8_t, secure_allocator_t<uint8_t> > hello_plaintext (
            |                                                                            ^
      /usr/include/c++/14/bits/alloc_traits.h:76:31: error: static assertion failed: allocator_traits<A>::rebind_alloc<A::value_type> must be A
         76 |                         _Tp>::value,
            |                               ^~~~~
      /usr/include/c++/14/bits/alloc_traits.h:76:31: note: ‘std::integral_constant<bool, false>::value’ evaluates to false
```

**Steps/Code to reproduce bug**

```
python3.12 -m venv .venv
source .venv/bin/activate
pip install torch torchaudio torchvision --index-url https://download.pytorch.org/whl/cu128
pip install nemo_toolkit[all]
deactivate
```

**Expected behavior**

nemo_toolkit should install and be usable.

**Environment overview (please complete the following information)**

 - Environment location: Bare-metal
 - Method of NeMo install: pip install -- see steps to reproduce

**Environment details**

Otherwise, please provide:
- OS version: Ubuntu 25.04
- PyTorch version: 2.7.0
- Python version: 3.12.7

**Additional context**

I've not been able to find a bug for this on the grpc issue tracker, but 1.41.0 is very old (Sep 25, 2021) with the latest being 1.70.2.

**Comment by rhdunn** [comment]
The pyzmq wheel has the same issue.

**Comment by rhdunn** [comment]
For pyzmq, version 25.1.1 is the minimum version that works on my environment; 25.1.0 fail with the dame error as grpcio.
