### ISSUE TITLE
Unexpected keyword arguments: `compute_on_step`   File "/home/muizz/nemo_workspace/Neural_net.py", line 9, in <module>     asr_model = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="QuartzNet15x5Base-En") ValueError: Unexpected keyword arguments: `compute_on_step`

### ISSUE THREAD

**Issue by muizzhaque** [NVIDIA/NeMo#6977]
I've been trying to transcribe a wav file of mono channel and rated a 16khz but this error shows up all the time
below is my code:
import nemo.collections.asr as nemo_asr
asr_model = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="QuartzNet15x5Base-En")
emb = asr_model.transcribe('./right_channel.wav')
print(emb)

error:
Unexpected keyword arguments: `compute_on_step`   File "/home/muizz/nemo_workspace/Neural_net.py", line 9, in <module>     asr_model = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="QuartzNet15x5Base-En") ValueError: Unexpected keyword arguments: `compute_on_step`

**Comment by titu1994** [comment]
There was a recent breaking update to torch metrics, we are fixing it in PR #6979

**Comment by muizzhaque** [comment]
okay

**Comment by titu1994** [comment]
This is merged now.

**Comment by muizzhaque** [comment]
I am still getting the error
Unexpected keyword arguments: `compute_on_step`
  File "/home/muizz/nemo_workspace/Neural_netw.py", line 9, in <module>
    asr_model = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="QuartzNet15x5Base-En")
ValueError: Unexpected keyword arguments: `compute_on_step`

**Comment by cxhagd** [comment]
how to solve this error?  i am confused .

**Comment by cxhagd** [comment]
i am still getting this error too!
