### ISSUE TITLE
TypeError while trying to run the GLUE Benchmark notebook in Google Colabs.

### ISSUE THREAD

**Issue by SnoozingSimian** [NVIDIA/NeMo#1343]
**Description**

The following error is reported when trying to run the GLUE benchmark notebook in Google Collab.
`TypeError: __init__() got an unexpected keyword argument 'accelerator'`

**Steps/Code to reproduce bug**

1. Open https://github.com/NVIDIA/NeMo.
2. Open the [GLUE benchmark notebook](https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/nlp/GLUE_Benchmark.ipynb) in Google Collab.
4. Run the required cells until the following code block is reached.
```# lets modify some trainer configs
# checks if we have GPU available and uses it
cuda = 1 if torch.cuda.is_available() else 0
config.trainer.gpus = cuda

config.trainer.precision = 16 if torch.cuda.is_available() else 32

# for mixed precision training, uncomment the line below (precision should be set to 16 and amp_level to O1):
# config.trainer.amp_level = O1

# remove distributed training flags
config.trainer.accelerator = None

# setup max number of steps to reduce training time for demonstration purposes of this tutorial
config.trainer.max_steps = 128

trainer = pl.Trainer(**config.trainer)
```

**Expected behavior**

The GLUE benchmark notebook should run without any errors.

**Environment overview (please complete the following information)**

 - Environment location: Google Collab
 - Method of NeMo install: `pip install nemo-toolkit[nlp]==1.0.0b1`

**Environment details**

- OS version: MacOS Catalina 10.15.7
- PyTorch version: 1.6.0+cu101
- Python version: Python 3.6.9

**Comment by FerchichiNourchene** [comment]
@Fackor I had this error while working with `pytorch_lightning==0.9.0`. Upgrading it to the `pytorch_lightning==1.0.3` solved the issue for me.
Hope that this will work for you too :)

**Comment by ericharper** [comment]
Hi, thanks for the issue. We have been working to pin the tutorial notebooks linked from the README to the correct version of NeMo and the correct version of the notebook. These changes are going into the next minor release. 

Please try the notebooks here: https://github.com/NVIDIA/NeMo/tree/v1.0.0b2 and let us know if you still have issues.
