### ISSUE TITLE
Discrepancy in Megatron-Core API in 24.02.01 NeMo Container vs GitHub & Error with upgraded package

### ISSUE THREAD

**Issue by viveknstarx** [NVIDIA/NeMo#13643]
Hi team,

I'm currently using the stable NeMo container version 24.02.01 and encountered two related issues regarding the Megatron-Core integration during fine-tuning.

🔹 Issue 1: Discrepancy in initialize_model_parallel()

When running the script examples/nlp/language_modeling/tuning/megatron_gpt_finetuning.py, everything was working fine up until a couple of weeks ago.

However, I recently encountered errors related to the Megatron-Core package — specifically, the initialize_model_parallel() function in megatron/core/parallel_state.py.

The version in the GitHub repository has the pipeline_model_parallel_comm_backend argument.

The container version of the function does not include this argument.

This mismatch suggests the version inside the container may be outdated or inconsistent with the corresponding NeMo repository.

🔹 Issue 2: TypeError after upgrading Megatron-Core

To resolve Issue 1, I upgraded the megatron-core package from version 0.11.0 to 0.12.0. While this fixed the initialize_model_parallel issue, I encountered a new error during validation:

TypeError: MCoreSelfAttentionMixin.forward() got an unexpected keyword argument 'inference_context'

Here’s the relevant traceback snippet:

File ".../transformer_layer.py", line 449, in _forward_attention
attention_output_with_bias = self.self_attention(
^^^^^^^^^^^^^^^^^^^^
File ".../transformer_layer.py", line 389, in forward
pre_mlp_layernorm_output, residual, context = self._forward_attention(*args, **kwargs)
...
TypeError: MCoreSelfAttentionMixin.forward() got an unexpected keyword argument 'inference_context'

This seems like an interface mismatch between NeMo and Megatron-Core after the version bump.

🛠️ Summary

NeMo container 24.02.01 includes an older/inconsistent version of Megatron-Core.

Upgrading Megatron-Core resolves one error but introduces another due to API mismatch in self-attention modules.

📌 Request

Could you clarify the recommended versions of Megatron-Core that are officially supported with NeMo 24.02.01? Also, is there a patch or update coming to resolve this inference_context compatibility issue?

Thank you for your support!

Let me know if you'd like to include pip freeze output or code snippets to help the maintainers reproduce the issue.

![Image](https://github.com/user-attachments/assets/44b3f6d5-1d64-40ae-a376-ae38f2be8a7a)
![Image](https://github.com/user-attachments/assets/1002c874-ffda-4476-8757-2be894aa27ac)
![Image](https://github.com/user-attachments/assets/84a6d297-6946-411a-b178-1860ea91c775)

**Comment by meatybobby** [comment]
NeMo container is expected to use NeMo and Megatron Core in the container. If you want to use newer Megatron Core which supports `pipeline_model_parallel_comm_backend`, you can use newer NeMo container 25.04.

**Comment by viveknstarx** [comment]
Thank you for the clarification.

Just one follow-up question: I'm currently using the NeMo container version 24.02.01, which previously worked fine with Megatron-Core 0.11.0. However, I'm now encountering an error related to pipeline_model_parallel_comm_backend, which seems unsupported.

I’d like to continue using the 24.02.01 container. Could you help me understand why this error is appearing now, even though the same Megatron-Core version was used before without issues? Has anything changed recently in the Megatron-Core or NeMo stack that could be causing this?

Appreciate your help in understanding this better.

**Comment by meatybobby** [comment]
Both NeMo 25.02.01 and Megatron Core 0.11.0 doesn't use pipeline_model_parallel_comm_backend.

NeMo added pipeline_model_parallel_comm_backend in this [commit](https://github.com/NVIDIA/NeMo/commit/e516ed1f9929db7ebad56cd2ffbfc251051ed6a1) on April.

I think you are running the script which isn't from the container.

The correct path of script is /opt/NeMo/examples/nlp/language_modeling/tuning/megatron_gpt_finetuning.py. If you directly run the script and NeMo package from github, you will get some NeMo and Megatron Core mismatch issue.

**Comment by viveknstarx** [comment]
Thanks for the clarification.

Just to confirm — I am indeed running the script from the correct path inside the container: /opt/NeMo/examples/nlp/language_modeling/tuning/megatron_gpt_finetuning.py (screenshot attached). However, I’m still getting the pipeline_model_parallel_comm_backend error, which suggests that the script references a newer NeMo API than what Megatron-Core 0.11.1 supports. So it seems the container has a mismatch between the script and the Megatron-Core version.

![Image](https://github.com/user-attachments/assets/df6f1975-fd9a-40cb-b677-02087f743cb7)

**Comment by viveknstarx** [comment]
i tried to ran it today again but now i am not facing that issue.i have no idea why. 🥲
